spring:
  application:
    name: SkidHomework
  data:
    mongodb:
      uri: mongodb://localhost:27017/skid-hw
  mail:
    # 发件邮箱配置
    # 部署时请修改这个
    host: smtp.example.com
    port: 587
    username: example
    password: password
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: false
# 数据库加密
# 实际部署的时候请务必修改这个,否则他人可能可以解密你的数据库
# openssl rand -base64 32
mongodb.encrypt:
  keys:
    - version: 1
      key: c8Ksz29RIti/vwkOw9h3o2vosQ+CYPljRJQCnpVvKdA=